name: tommypemberton
favicon: null
layout_spectrum: 0.25216
typography_spectrum: 0.59495
title: Tommy Pemberton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#304556'
    - '#898e87'
    - '#cac0b4'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
