name: tommypemberton
favicon: null
layout_spectrum: 0.25216
typography_spectrum: 0.59495
title: Tommy Pemberton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
